CupCarbon v. Twin IoT 6.52
----------------
name:reto 3
zoom:2
centerposition_la:4.5975705808120475
centerposition_lo:-74.05955672264099
map:1
display_details:true
draw_radio_links:true
draw_sensor_arrows:false
radio_links_color:2
draw_marker_arrows:false
display_rl_distance:true
propagation:false
display_marker_distance:false
display_radio_messages:true
draw_script_file_name:true
display_print_messages:true
display_all_routes:false
